# -*- coding: utf-8 -*-
"""MUTESI Florance 2401000259.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18R67XfXOdKJ1ZPmQQfyJYbloCEdXuwFh
"""

st import re
from collections import Counter

def preprocess_text(text):
    """Lowercase, remove punctuation, and split text into words."""
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text)
    words = text.split()
    return words

def jaccard_similarity(text1, text2):
    """Calculate Jaccard similarity between two texts."""
    words1 = preprocess_text(text1)
    words2 = preprocess_text(text2)

    set1 = set(words1)
    set2 = set(words2)

    intersection = len(set1.intersection(set2))
    union = len(set1.union(set2))

    if union == 0:
        return 0.0
    return intersection / union

def word_frequency_similarity(text1, text2):
    """Calculate similarity based on word frequency."""
    words1 = preprocess_text(text1)
    words2 = preprocess_text(text2)

    count1 = Counter(words1)
    count2 = Counter(words2)

    common_words = set(count1.keys()) & set(count2.keys())
    similarity_sum = 0
    for word in common_words:
        similarity_sum += min(count1[word], count2[word])

    total_words1 = sum(count1.values())
    total_words2 = sum(count2.values())

    if total_words1 == 0 or total_words2 == 0:
        return 0.0

    return similarity_sum / max(total_words1, total_words2)


def main():
    file1_path = input("Enter the path to the first text file (e.g., University of Kigali): ")
    file2_path = input("Enter the path to the second text file (e.g., Gasabo): ")

    try:
        with open(file1_path, 'r', encoding='utf-8') as file1, open(file2_path, 'r', encoding='utf-8') as file2:
            text1 = file1.read()
            text2 = file2.read()

        jaccard_sim = jaccard_similarity(text1, text2)
        freq_sim = word_frequency_similarity(text1, text2)

        print(f"Jaccard Similarity: {jaccard_sim}")
        print(f"Word Frequency Similarity: {freq_sim}")

    except FileNotFoundError:
        print("One or both files not found. Please make sure the file paths are correct.")
    except Exception as e:
        print(f"An error occurred: {e}")


if University of Kigali=="Gasabo":
    main(Gasabo)

